name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    name: Build and Package Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t filoger-smart-website:latest .

      - name: Push Docker Image
        run: |
          docker tag filoger-smart-website:latest ${{ secrets.DOCKER_USERNAME }}/filoger-smart-website:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/filoger-smart-website:latest

  deploy:
    name: Deploy to Linux Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to the server
        uses: appleboy/scp-action@v0.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./
          target: ~/filoger-smart-website

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/filoger-smart-website
            docker pull ${{ secrets.DOCKER_USERNAME }}/filoger-smart-website:latest
            docker stop filoger-smart-website || true
            docker rm filoger-smart-website || true
            docker run -d --name filoger-smart-website -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/filoger-smart-website:latest

